base: &base
  adapter: postgresql
  encoding: unicode
  username: postgres

development:
  database: cdq_server_development
  <<: *base

test:
  database: cdq_server_test
  <<: *base

staging:
  database: cdq_server_staging
  <<: *base
